# Copyright 2018-2022 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes the AppDynamics Agent and configures it to connect to the service"
  homepage = "https://github.com/paketo-buildpacks/appdynamics"
  id = "paketo-buildpacks/appdynamics"
  keywords = ["appdynamics", "agent", "apm", "java", "nodejs"]
  name = "Paketo Buildpack for AppDynamics"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/appdynamics/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/helper", "bin/main", "buildpack.toml", "resources/app-agent-config.xml", "resources/custom-activity-correlation.xml", "resources/log4j2.xml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    description = "the AppDynamics application name"
    launch = true
    name = "APPDYNAMICS_AGENT_APPLICATION_NAME"

  [[metadata.configurations]]
    description = "the AppDynamics node name"
    launch = true
    name = "APPDYNAMICS_AGENT_NODE_NAME"

  [[metadata.configurations]]
    description = "the AppDynamics tier name"
    launch = true
    name = "APPDYNAMICS_AGENT_TIER_NAME"

  [[metadata.configurations]]
    build = true
    description = "the SHA256 hash of the external AppDynamics configuration archive"
    name = "BP_APPD_EXT_CONF_SHA256"

  [[metadata.configurations]]
    build = true
    default = "0"
    description = "the number of directory components to strip from the external AppDynamics configuration archive"
    name = "BP_APPD_EXT_CONF_STRIP"

  [[metadata.configurations]]
    build = true
    description = "the download location of the external AppDynamics configuration"
    name = "BP_APPD_EXT_CONF_URI"

  [[metadata.configurations]]
    build = true
    description = "the version of the external AppDynamics configuration"
    name = "BP_APPD_EXT_CONF_VERSION"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:appdynamics:java-agent:22.12.0:*:*:*:*:*:*:*"]
    id = "appdynamics-java"
    name = "AppDynamics Java Agent"
    purl = "pkg:generic/appdynamics-java-agent@22.12.0?arch=amd64"
    sha256 = "4d52c8c8153fcc801b6c0c4043fa0ed26b5166c7e6952f6d995b28068e54b8db"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://download.run.pivotal.io/appdynamics/appdynamics-22.12.0-34603.tar.gz"
    version = "22.12.0"

    [[metadata.dependencies.licenses]]
      uri = "https://docs.appdynamics.com/display/PRO45/License+Entitlements+and+Restrictions"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:appdynamics:nodejs-agent:23.3.0:*:*:*:*:*:*:*"]
    id = "appdynamics-nodejs"
    name = "AppDynamics NodeJS Agent"
    purl = "pkg:generic/appdynamics-nodejs-agent@23.3.0?arch=amd64"
    sha256 = "fe11a1895a563d03debe75be3053dcd4234e46c3ea832acd940361b592420605"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://registry.npmjs.org/appdynamics/-/appdynamics-23.3.0.tgz"
    version = "23.3.0"

    [[metadata.dependencies.licenses]]
      uri = "https://docs.appdynamics.com/display/PRO45/License+Entitlements+and+Restrictions"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:appdynamics:php-agent:23.2.0:*:*:*:*:*:*:*"]
    id = "appdynamics-php"
    name = "AppDynamics PHP Agent"
    purl = "pkg:generic/appdynamics-php-agent@23.2.0?arch=amd64"
    sha256 = "50ad2d9c262fa9a15d58ac1b944d9b72f34c072503284bda9a349f7865e65f50"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://download.run.pivotal.io/appdynamics-php/appdynamics-23.2.0-684.tar.bz2"
    version = "23.2.0"

    [[metadata.dependencies.licenses]]
      uri = "https://docs.appdynamics.com/display/PRO45/License+Entitlements+and+Restrictions"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"
